### ISSUE TITLE
Request Add Support for FontAwesome 5 free and Pro

### ISSUE THREAD

**Issue by shaneoliver** [htmlburger/carbon-field-icon#3]
The names of the FontAwesome classes have changed to include the weight. For example fas far fal. When trying to render a icon from Carbon Field Icon we are only given 'fa fa-selected-icon-name'. Further, there are many new icons in the free version, and even more in Pro. Can we expect support for FontAwesome 5?

**Comment by dmhendricks** [comment]
I'd be happy to create a JSON definition file for, at minimum, FA5 Free and probably also Pro. However, I won't be able to get to it right away. I will put it on my list.

**Comment by jorostoyanov** [comment]
Hey Guys!

We have just released v3 of the library which adds support for Carbon Fields v3 as well as icon providers support -- https://github.com/htmlburger/carbon-field-icon/releases/tag/v3.0.0.

Out of the box, FontAwesome v5.8.1 is currently included.

Since the PRO version requires a license, we haven't added support for it, however, you can register a custom set of icons in order to achieve that.

Check out the README and feel free to open a new issue if you have any questions!

Cheers 🎉
